!=======================================================================
! Generated by  : PSCAD v4.5.0.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : abc
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE abcDyn(d, q, theta, a, b, c)

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: d, q, theta
      REAL,    INTENT(OUT) :: a, b, c

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, RT_11
      REAL     RT_12, RT_13, RT_14, RT_15, RT_16
      REAL     RT_17, RT_18, RT_19, RT_20, RT_21
      REAL     RT_22, RT_23

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF                               ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 29
      NNODE     = NNODE + 2

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      a        = STOF(ISTOF + 4)
      b        = STOF(ISTOF + 5)
      c        = STOF(ISTOF + 6)
      RT_1     = STOF(ISTOF + 7)
      RT_2     = STOF(ISTOF + 8)
      RT_3     = STOF(ISTOF + 9)
      RT_4     = STOF(ISTOF + 10)
      RT_5     = STOF(ISTOF + 11)
      RT_6     = STOF(ISTOF + 12)
      RT_7     = STOF(ISTOF + 13)
      RT_8     = STOF(ISTOF + 14)
      RT_9     = STOF(ISTOF + 15)
      RT_10    = STOF(ISTOF + 16)
      RT_11    = STOF(ISTOF + 17)
      RT_12    = STOF(ISTOF + 18)
      RT_13    = STOF(ISTOF + 19)
      RT_14    = STOF(ISTOF + 20)
      RT_15    = STOF(ISTOF + 21)
      RT_16    = STOF(ISTOF + 22)
      RT_17    = STOF(ISTOF + 23)
      RT_18    = STOF(ISTOF + 24)
      RT_19    = STOF(ISTOF + 25)
      RT_20    = STOF(ISTOF + 26)
      RT_21    = STOF(ISTOF + 27)
      RT_22    = STOF(ISTOF + 28)
      RT_23    = STOF(ISTOF + 29)

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'abc.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 
      RT_20 = PI2_BY3

! 50:[emtconst] Commonly Used Constants (pi...) 
      RT_21 = PI2_BY3

! 60:[emtconst] Commonly Used Constants (pi...) 
      RT_22 = PI2_BY3

! 70:[emtconst] Commonly Used Constants (pi...) 
      RT_23 = PI2_BY3

! 80:[trig] Trigonometric Functions 
!  Trig-Func
      RT_1 = COS(theta)
!

! 90:[mult] Multiplier 
      RT_3 = RT_1 * d

! 100:[trig] Trigonometric Functions 
!  Trig-Func
      RT_2 = SIN(theta)
!

! 110:[mult] Multiplier 
      RT_4 = RT_2 * q

! 120:[sumjct] Summing/Differencing Junctions 
      RT_11 = + theta - RT_20

! 130:[trig] Trigonometric Functions 
!  Trig-Func
      RT_6 = COS(RT_11)
!

! 140:[mult] Multiplier 
      RT_8 = RT_6 * d

! 150:[sumjct] Summing/Differencing Junctions 
      RT_12 = + theta - RT_21

! 160:[trig] Trigonometric Functions 
!  Trig-Func
      RT_7 = SIN(RT_12)
!

! 170:[mult] Multiplier 
      RT_9 = RT_7 * q

! 180:[sumjct] Summing/Differencing Junctions 
      RT_18 = + theta + RT_22

! 190:[trig] Trigonometric Functions 
!  Trig-Func
      RT_13 = COS(RT_18)
!

! 200:[mult] Multiplier 
      RT_15 = RT_13 * d

! 210:[sumjct] Summing/Differencing Junctions 
      RT_19 = + theta + RT_23

! 220:[trig] Trigonometric Functions 
!  Trig-Func
      RT_14 = SIN(RT_19)
!

! 230:[mult] Multiplier 
      RT_16 = RT_14 * q

! 240:[sumjct] Summing/Differencing Junctions 
      RT_5 = + RT_3 - RT_4

! 250:[sumjct] Summing/Differencing Junctions 
      RT_17 = + RT_15 - RT_16

! 260:[sumjct] Summing/Differencing Junctions 
      RT_10 = + RT_8 - RT_9

! 270:[gain] Gain Block 
!  Gain
      a = 1.0 * RT_5

! 280:[gain] Gain Block 
!  Gain
      c = 1.0 * RT_17

! 300:[gain] Gain Block 
!  Gain
      b = 1.0 * RT_10

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = d
      STOF(ISTOF + 2) = q
      STOF(ISTOF + 3) = theta
      STOF(ISTOF + 4) = a
      STOF(ISTOF + 5) = b
      STOF(ISTOF + 6) = c
      STOF(ISTOF + 7) = RT_1
      STOF(ISTOF + 8) = RT_2
      STOF(ISTOF + 9) = RT_3
      STOF(ISTOF + 10) = RT_4
      STOF(ISTOF + 11) = RT_5
      STOF(ISTOF + 12) = RT_6
      STOF(ISTOF + 13) = RT_7
      STOF(ISTOF + 14) = RT_8
      STOF(ISTOF + 15) = RT_9
      STOF(ISTOF + 16) = RT_10
      STOF(ISTOF + 17) = RT_11
      STOF(ISTOF + 18) = RT_12
      STOF(ISTOF + 19) = RT_13
      STOF(ISTOF + 20) = RT_14
      STOF(ISTOF + 21) = RT_15
      STOF(ISTOF + 22) = RT_16
      STOF(ISTOF + 23) = RT_17
      STOF(ISTOF + 24) = RT_18
      STOF(ISTOF + 25) = RT_19
      STOF(ISTOF + 26) = RT_20
      STOF(ISTOF + 27) = RT_21
      STOF(ISTOF + 28) = RT_22
      STOF(ISTOF + 29) = RT_23

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE abcOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'abc.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------


!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE abcDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_20, RT_21, RT_22, RT_23

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 
      RT_20 = PI2_BY3

! 50:[emtconst] Commonly Used Constants (pi...) 
      RT_21 = PI2_BY3

! 60:[emtconst] Commonly Used Constants (pi...) 
      RT_22 = PI2_BY3

! 70:[emtconst] Commonly Used Constants (pi...) 
      RT_23 = PI2_BY3

! 80:[trig] Trigonometric Functions 

! 90:[mult] Multiplier 

! 100:[trig] Trigonometric Functions 

! 110:[mult] Multiplier 

! 120:[sumjct] Summing/Differencing Junctions 

! 130:[trig] Trigonometric Functions 

! 140:[mult] Multiplier 

! 150:[sumjct] Summing/Differencing Junctions 

! 160:[trig] Trigonometric Functions 

! 170:[mult] Multiplier 

! 180:[sumjct] Summing/Differencing Junctions 

! 190:[trig] Trigonometric Functions 

! 200:[mult] Multiplier 

! 210:[sumjct] Summing/Differencing Junctions 

! 220:[trig] Trigonometric Functions 

! 230:[mult] Multiplier 

! 240:[sumjct] Summing/Differencing Junctions 

! 250:[sumjct] Summing/Differencing Junctions 

! 260:[sumjct] Summing/Differencing Junctions 

! 270:[gain] Gain Block 

! 280:[gain] Gain Block 

! 300:[gain] Gain Block 

      RETURN
      END

!=======================================================================

      SUBROUTINE abcOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


      RETURN
      END

