!=======================================================================
! Generated by  : PSCAD v4.5.0.0
!
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : DQ
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE DQDyn(a, b, c, theta, d, q)

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: a, b, c, theta
      REAL,    INTENT(OUT) :: d, q

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, RT_11
      REAL     RT_12, RT_13, RT_14, RT_15, RT_16
      REAL     RT_17, RT_18, RT_19, RT_20, RT_21
      REAL     RT_22, RT_23

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF                               ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 29
      NNODE     = NNODE + 2

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------

      d        = STOF(ISTOF + 5)
      q        = STOF(ISTOF + 6)
      RT_1     = STOF(ISTOF + 7)
      RT_2     = STOF(ISTOF + 8)
      RT_3     = STOF(ISTOF + 9)
      RT_4     = STOF(ISTOF + 10)
      RT_5     = STOF(ISTOF + 11)
      RT_6     = STOF(ISTOF + 12)
      RT_7     = STOF(ISTOF + 13)
      RT_8     = STOF(ISTOF + 14)
      RT_9     = STOF(ISTOF + 15)
      RT_10    = STOF(ISTOF + 16)
      RT_11    = STOF(ISTOF + 17)
      RT_12    = STOF(ISTOF + 18)
      RT_13    = STOF(ISTOF + 19)
      RT_14    = STOF(ISTOF + 20)
      RT_15    = STOF(ISTOF + 21)
      RT_16    = STOF(ISTOF + 22)
      RT_17    = STOF(ISTOF + 23)
      RT_18    = STOF(ISTOF + 24)
      RT_19    = STOF(ISTOF + 25)
      RT_20    = STOF(ISTOF + 26)
      RT_21    = STOF(ISTOF + 27)
      RT_22    = STOF(ISTOF + 28)
      RT_23    = STOF(ISTOF + 29)

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'DQ.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 50:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = PI2_BY3

! 60:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = PI2_BY3

! 70:[trig] Trigonometric Functions 
!  Trig-Func
      RT_19 = SIN(theta)
!

! 80:[mult] Multiplier 
      RT_9 = RT_19 * a

! 90:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = PI2_BY3

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_8 = PI2_BY3

! 110:[trig] Trigonometric Functions 
!  Trig-Func
      RT_14 = COS(theta)
!

! 120:[mult] Multiplier 
      RT_3 = RT_14 * a

! 130:[sumjct] Summing/Differencing Junctions 
      RT_15 = + theta - RT_1

! 140:[trig] Trigonometric Functions 
!  Trig-Func
      RT_16 = COS(RT_15)
!

! 150:[mult] Multiplier 
      RT_4 = RT_16 * b

! 160:[sumjct] Summing/Differencing Junctions 
      RT_17 = + theta + RT_2

! 170:[trig] Trigonometric Functions 
!  Trig-Func
      RT_18 = COS(RT_17)
!

! 180:[mult] Multiplier 
      RT_5 = RT_18 * c

! 190:[sumjct] Summing/Differencing Junctions 
      RT_20 = + theta - RT_7

! 200:[trig] Trigonometric Functions 
!  Trig-Func
      RT_21 = SIN(RT_20)
!

! 210:[mult] Multiplier 
      RT_10 = RT_21 * b

! 220:[sumjct] Summing/Differencing Junctions 
      RT_22 = + theta + RT_8

! 230:[trig] Trigonometric Functions 
!  Trig-Func
      RT_23 = SIN(RT_22)
!

! 240:[mult] Multiplier 
      RT_11 = RT_23 * c

! 250:[sumjct] Summing/Differencing Junctions 
      RT_6 = + RT_3 + RT_4 + RT_5

! 260:[sumjct] Summing/Differencing Junctions 
      RT_12 = + RT_9 + RT_10 + RT_11

! 270:[gain] Gain Block 
!  Gain
      RT_13 = -1.0 * RT_12

! 280:[gain] Gain Block 
!  Gain
      q = 0.6666667 * RT_13

! 290:[gain] Gain Block 
!  Gain
      d = 0.6666667 * RT_6

!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------

      STOF(ISTOF + 1) = a
      STOF(ISTOF + 2) = b
      STOF(ISTOF + 3) = c
      STOF(ISTOF + 4) = theta
      STOF(ISTOF + 5) = d
      STOF(ISTOF + 6) = q
      STOF(ISTOF + 7) = RT_1
      STOF(ISTOF + 8) = RT_2
      STOF(ISTOF + 9) = RT_3
      STOF(ISTOF + 10) = RT_4
      STOF(ISTOF + 11) = RT_5
      STOF(ISTOF + 12) = RT_6
      STOF(ISTOF + 13) = RT_7
      STOF(ISTOF + 14) = RT_8
      STOF(ISTOF + 15) = RT_9
      STOF(ISTOF + 16) = RT_10
      STOF(ISTOF + 17) = RT_11
      STOF(ISTOF + 18) = RT_12
      STOF(ISTOF + 19) = RT_13
      STOF(ISTOF + 20) = RT_14
      STOF(ISTOF + 21) = RT_15
      STOF(ISTOF + 22) = RT_16
      STOF(ISTOF + 23) = RT_17
      STOF(ISTOF + 24) = RT_18
      STOF(ISTOF + 25) = RT_19
      STOF(ISTOF + 26) = RT_20
      STOF(ISTOF + 27) = RT_21
      STOF(ISTOF + 28) = RT_22
      STOF(ISTOF + 29) = RT_23

!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE DQOut()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2

!---------------------------------------
! Transfers from storage arrays
!---------------------------------------


!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Configuration of Models
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'DQ.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage
!---------------------------------------


!---------------------------------------
! Close Model Data read
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE DQDyn_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_7, RT_8

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


! 50:[emtconst] Commonly Used Constants (pi...) 
      RT_1 = PI2_BY3

! 60:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = PI2_BY3

! 70:[trig] Trigonometric Functions 

! 80:[mult] Multiplier 

! 90:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = PI2_BY3

! 100:[emtconst] Commonly Used Constants (pi...) 
      RT_8 = PI2_BY3

! 110:[trig] Trigonometric Functions 

! 120:[mult] Multiplier 

! 130:[sumjct] Summing/Differencing Junctions 

! 140:[trig] Trigonometric Functions 

! 150:[mult] Multiplier 

! 160:[sumjct] Summing/Differencing Junctions 

! 170:[trig] Trigonometric Functions 

! 180:[mult] Multiplier 

! 190:[sumjct] Summing/Differencing Junctions 

! 200:[trig] Trigonometric Functions 

! 210:[mult] Multiplier 

! 220:[sumjct] Summing/Differencing Junctions 

! 230:[trig] Trigonometric Functions 

! 240:[mult] Multiplier 

! 250:[sumjct] Summing/Differencing Junctions 

! 260:[sumjct] Summing/Differencing Junctions 

! 270:[gain] Gain Block 

! 280:[gain] Gain Block 

! 290:[gain] Gain Block 

      RETURN
      END

!=======================================================================

      SUBROUTINE DQOut_Begin()

!---------------------------------------
! Standard includes
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISUBS                               ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices
!---------------------------------------


! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2

!---------------------------------------
! Electrical Node Lookup
!---------------------------------------


!---------------------------------------
! Generated code from module definition
!---------------------------------------


      RETURN
      END

